LANGUAGES = {
    'pt': {
        'file_manager': 'Gerenciador de Arquivos',
        'new_folder': 'Nova pasta',
        'create': 'Criar pasta',
        'upload': 'Enviar',
        'path': 'Caminho:',
        'parent_directory': 'Diretório Pai',
        'name': 'Nome',
        'size': 'Tamanho',
        'type': 'Tipo',
        'modified': 'Data de Modificação',
        'folder': 'Pasta',
        'overwrite_message': 'O arquivo "{filename}" já existe. Deseja sobrescrever?',
        'yes': 'Sim',
        'no': 'Não',
        'drag_drop': 'Arraste os arquivos aqui para enviar.',
        'folder_creation_disabled': 'Criação de pastas desabilitada',
        'invalid_folder_name': 'Nome da pasta inválido',
    },
    'en': {
        'file_manager': 'File Manager',
        'new_folder': 'New Folder',
        'create': 'Create Folder',
        'upload': 'Upload',
        'path': 'Path:',
        'parent_directory': 'Parent Directory',
        'name': 'Name',
        'size': 'Size',
        'type': 'Type',
        'modified': 'Last Modified',
        'folder': 'Folder',
        'overwrite_message': 'File "{filename}" already exists. Overwrite?',
        'yes': 'Yes',
        'no': 'No',
        'drag_drop': 'Drag and drop files here to upload.',
        'folder_creation_disabled': 'Folder creation is disabled',
        'invalid_folder_name': 'Invalid folder name',
    },
    'es': {
        'file_manager': 'Administrador de Archivos',
        'new_folder': 'Nueva Carpeta',
        'create': 'Crear Carpeta',
        'upload': 'Subir',
        'path': 'Ruta:',
        'parent_directory': 'Directorio Padre',
        'name': 'Nombre',
        'size': 'Tamaño',
        'type': 'Tipo',
        'modified': 'Fecha de Modificación',
        'folder': 'Carpeta',
        'overwrite_message': 'El archivo "{filename}" ya existe. ¿Desea sobrescribirlo?',
        'yes': 'Sí',
        'no': 'No',
        'drag_drop': 'Arrastra los archivos aquí para subir.',
        'folder_creation_disabled': 'La creación de carpetas está deshabilitada',
        'invalid_folder_name': 'Nombre de carpeta inválido',
    }
}
